In [1]:
import tensorflow
tensorflow.__version__

'1.15.0'

In [9]:
weightss = [0.05,0.4,0.05,0.25,0.25]
def weighted_categorical_crossentropy(weights):
    def wcce(y_true, y_pred):
        Kweights = K.constant(weights)
        if not K.is_tensor(y_pred): y_pred = K.constant(y_pred)
        y_true = K.cast(y_true, y_pred.dtype)
        return K.sparse_categorical_crossentropy(y_true, y_pred) * K.sum(y_true * Kweights, axis=-1)
    return wcce

In [10]:
def FocalLoss11(targets, inputs, alpha=.5, gamma=2):    
    #targets = K.cast(targets, 'float32')
    BCE = K.sparse_categorical_crossentropy(targets, inputs)
    BCE_EXP = K.exp(-BCE)
    focal_loss = K.mean(alpha * K.pow((1-BCE_EXP), gamma) * BCE)
    return focal_loss

In [31]:
from sklearn.utils import class_weight


def FocalLoss_weighted(targets, inputs, gamma=2): 
    #class_weights = class_weight.compute_class_weight('balanced',
     #                                            np.unique(inputs[0,:,0]),
      #                                           inputs[0,:,0])
    alpha = tf.constant([[.1],[.6],[.1],[.3],[.3]], dtype=tf.float32)
    #alpha = tf.constant([class_weights], dtype=tf.float32)
    #alpha=tf.constant([.1,.3,.1,.25,.25], dtype=tf.float32)
    #targets = K.cast(targets, 'float32')
    BCE = K.sparse_categorical_crossentropy(targets, inputs)
    BCE_EXP = K.exp(-BCE)
    focal_loss = K.mean(tf.matmul(alpha , K.pow((1-BCE_EXP), gamma) * BCE))
    return focal_loss

In [ ]:
def plot_confusion_matrix(cm, classes,
                          normalize=False,
                          title='Confusion matrix',
                          cmap=plt.cm.Blues):
    """
    This function prints and plots the confusion matrix.
    Normalization can be applied by setting `normalize=True`.
    """
    if normalize:
        cm = cm.astype('float') / cm.sum(axis=1)[:, np.newaxis]
        print("Normalized confusion matrix")
    else:
        print('Confusion matrix, without normalization')

    print(cm)

    plt.imshow(cm, interpolation='nearest', cmap=cmap)
    plt.title(title)
    plt.colorbar()
    tick_marks = np.arange(len(classes))
    plt.xticks(tick_marks, classes, rotation=45)
    plt.yticks(tick_marks, classes)
    fmt = '.2f' if normalize else 'd'
    thresh = cm.max() / 2.
    for i, j in itertools.product(range(cm.shape[0]), range(cm.shape[1])):
        plt.text(j, i, format(cm[i, j], fmt),
                 horizontalalignment="center",
                 color="white" if cm[i, j] > thresh else "black")
    plt.ylabel('True label')
    plt.xlabel('Predicted label')
    plt.tight_layout()

# focal_loss20fold

In [108]:
%cd C:\Users\Admin\Desktop\ebrahi
from keras import backend as K
import models 
import ASSC_bach_generetor
model=model_TCNN_CRF()
model.compile(optimizers.Adam(0.001,amsgrad=True),loss=FocalLoss11, metrics=[crf_marginal_accuracy])


#/pure_aa
import gc
import random
base_path = "20fold"    
files = sorted(glob(os.path.join(base_path, "*.npz")))
j=0
gt_t=[]
preds_t=[]
preds_cat_cat=[]
kk=0
for i in range(20):
        ids = sorted(list(set([x.split("/")[-1][:5] for x in files])))
        ids=[x for x in files if x.split("/")[-1][:5] in ids]
        if kk<38:
            d=ids[kk:kk+2]
            idea=ids[kk+2:]+ids[0:kk]
            val=[idea.pop(int(kk/2)),idea.pop(int(kk/2)+1)]
            val_dict={k: np.load(k) for k in val}
            train_dict = {k: np.load(k) for k in idea}    
            test_dict = {k: np.load(k) for k in d}
        else :
            idea=ids[:38]
            d=ids[38]
            val=[idea.pop(int(kk/2)),idea.pop(int(kk/2)+1)]
            val_dict={k: np.load(k) for k in val}
            train_dict = {k: np.load(k) for k in idea}
            test_dict = {k: np.load(k) for k in [d]}
        kk=kk+2
        file_path = "bala.h5"
        checkpoint = ModelCheckpoint(file_path, monitor='acc',verbose=1, save_best_only=True, mode='max')
        early = EarlyStopping(monitor='acc', mode="max", patience=20, verbose=1)
        redonplat = ReduceLROnPlateau(monitor='acc', mode="max", factor=0.1, patience=4, verbose=2)#, factor=0.2
        callbacks_list = [checkpoint, early ,redonplat]
        
        model = get_base_model()
        
        #model.fit_generator(gen_balance(train_dict),validation_data=gen_j(val_dict),epochs=1,verbose=2,
         #                            steps_per_epoch=1000,validation_steps=300, callbacks=callbacks_list) 

        K.clear_session()
        del model
        
        gc.collect()
        file_path = "model1.h5"
        
        checkpoint = ModelCheckpoint(file_path, monitor='val_crf_marginal_accuracy',verbose=1, save_best_only=True, mode='max')
        early = EarlyStopping(monitor='val_crf_marginal_accuracy', mode="max", patience=20, verbose=1)
        redonplat = ReduceLROnPlateau(monitor='val_crf_marginal_accuracy', mode="max", factor=0.5, patience=4, verbose=2)#, factor=0.2
        callbacks_list = [checkpoint, early ,redonplat]
        model = get_base_model()
        model.fit_generator(gen_generator(train_dict),validation_data=gen_j(val_dict),epochs=25,verbose=2,
                                     steps_per_epoch=1000,validation_steps=300, callbacks=callbacks_list)
        
        K.clear_session()
        del model
        gc.collect()
        file_path = "model0.h5"
        checkpoint = ModelCheckpoint(file_path, monitor='val_crf_marginal_accuracy',verbose=1, save_best_only=True, mode='max')
        early = EarlyStopping(monitor='val_crf_marginal_accuracy', mode="max", patience=20, verbose=1)
        redonplat = ReduceLROnPlateau(monitor='val_crf_marginal_accuracy', mode="max", factor=0.5, patience=4, verbose=2)#, factor=0.2
        callbacks_list = [checkpoint, early ,redonplat]
        model = get_base_model()
        #model.load_weights('bala.h5')
        model.fit_generator(gen_j(train_dict),validation_data=gen_j(val_dict),epochs=25,verbose=2,
                                      steps_per_epoch=1000,validation_steps=300, callbacks=callbacks_list) 
        
        K.clear_session()
        del model
        gc.collect()
        
        h=0
        j=0
        gg=[]
        g=[]
        p=[]
        p_cat=[]
        for record in tqdm(test_dict):
                all_rows = test_dict[record]['x']
                
              
                l=0
                j=j+1
                for batch_hyp in chunker(range(all_rows.shape[0])):
                        l=l+1
                        X1 = all_rows[min(batch_hyp):max(batch_hyp)+1, ...]
                        Y1= test_dict[record]['y'][min(batch_hyp):max(batch_hyp)+1]
                        
                        #######################################
                        X1 =rescale_array2(X1)
                        X1 = np.expand_dims(X1, 0)
           
                        model = get_base_model()
                        model.load_weights('model1.h5')
                        Y_pred1 = model.predict([X1,X1])
                        model.load_weights('model0.h5')
                        Y_pred0 = model.predict([X1,X1])
                      
                        Y_pred=Y_pred1 +Y_pred0
                        Y_pred = Y_pred.argmax(axis=-1).ravel().tolist()
                        
                        gt_t += Y1.ravel().tolist()
                        preds_t += Y_pred
                        g+=Y1.ravel().tolist()
                        p+=Y_pred
      #####
        print(test_dict)
        f1 = f1_score(g, p, average="macro")
        print("Seq Test f1 score (deep): %s "% f1)
        acc = accuracy_score(g, p)
        print("Seq Test accuracy score(deeo) : %s "% acc)
        print(classification_report(g, p))
        cnf_matrix = confusion_matrix(g, p)
        np.set_printoptions(precision=2)
        print(cnf_matrix)
        from keras import backend as K 
        K.clear_session()
        del model
f1 = f1_score(gt_t, preds_t, average="macro")
print("Seq Test f1 score : %s "% f1)
acc = accuracy_score(gt_t, preds_t)
print("Seq Test accuracy score : %s "% acc)
print(classification_report(gt_t, preds_t))
class_names=np.array([["W"], ["S1"],["S2"],["S3"],["R"]])
# Compute confusion matrix
import itertools
from sklearn.metrics import confusion_matrix



cnf_matrix = confusion_matrix(gt_t, preds_t)
print(cnf_matrix)

C:\Users\Admin\Desktop\ebrahi
Epoch 1/25
 - 246s - loss: 0.4325 - crf_marginal_accuracy: 0.5651 - val_loss: 0.1620 - val_crf_marginal_accuracy: 0.7008

Epoch 00001: val_crf_marginal_accuracy improved from -inf to 0.70080, saving model to model1.h5
Epoch 2/25
 - 243s - loss: 0.2211 - crf_marginal_accuracy: 0.6395 - val_loss: 0.7285 - val_crf_marginal_accuracy: 0.7114

Epoch 00002: val_crf_marginal_accuracy improved from 0.70080 to 0.71143, saving model to model1.h5
Epoch 3/25
 - 239s - loss: 0.1993 - crf_marginal_accuracy: 0.6570 - val_loss: 0.1060 - val_crf_marginal_accuracy: 0.7277

Epoch 00003: val_crf_marginal_accuracy improved from 0.71143 to 0.72767, saving model to model1.h5
Epoch 4/25
 - 238s - loss: 0.1909 - crf_marginal_accuracy: 0.7017 - val_loss: 0.0947 - val_crf_marginal_accuracy: 0.7387

Epoch 00004: val_crf_marginal_accuracy improved from 0.72767 to 0.73873, saving model to model1.h5
Epoch 5/25
 - 245s - loss: 0.1717 - crf_marginal_accuracy: 0.7321 - val_loss: 0.1385 - va

100%|██████████| 2/2 [04:08<00:00, 124.07s/it]


{'20fold\\SC4001E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028E9E064708>, '20fold\\SC4002E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028E9E064B48>}
Seq Test f1 score (deep): 0.7961537098391454 
Seq Test accuracy score(deeo) : 0.8572154471544715 
              precision    recall  f1-score   support

           0       0.93      0.89      0.91       371
           1       0.55      0.38      0.45       117
           2       0.84      0.88      0.86       623
           3       0.93      0.84      0.88       517
           4       0.80      0.98      0.88       340

    accuracy                           0.86      1968
   macro avg       0.81      0.79      0.80      1968
weighted avg       0.86      0.86      0.85      1968

[[329  21   0   1  20]
 [ 21  45  14   0  37]
 [  1  16 547  32  27]
 [  2   0  81 433   1]
 [  0   0   7   0 333]]
Epoch 1/25
 - 309s - loss: 0.4050 - crf_marginal_accuracy: 0.5416 - val_loss: 0.5268 - val_crf_marginal_accuracy: 0.5760

Epoch 00001: v

100%|██████████| 2/2 [05:24<00:00, 162.45s/it]


{'20fold\\SC4011E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028E9E0646C8>, '20fold\\SC4012E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028E9E064108>}
Seq Test f1 score (deep): 0.8304234229036835 
Seq Test accuracy score(deeo) : 0.8807339449541285 
              precision    recall  f1-score   support

           0       0.91      0.87      0.89       319
           1       0.73      0.58      0.65       201
           2       0.95      0.91      0.93      1222
           3       0.75      0.89      0.81       201
           4       0.81      0.97      0.88       346

    accuracy                           0.88      2289
   macro avg       0.83      0.84      0.83      2289
weighted avg       0.88      0.88      0.88      2289

[[ 277   26    1   13    2]
 [  20  116   32    1   32]
 [   6   13 1110   47   46]
 [   0    0   22  179    0]
 [   2    3    7    0  334]]
Epoch 1/25
 - 293s - loss: 0.5360 - crf_marginal_accuracy: 0.4727 - val_loss: 0.4057 - val_crf_marginal_accurac

100%|██████████| 2/2 [04:40<00:00, 140.41s/it]


{'20fold\\SC4021E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1754E708>, '20fold\\SC4022E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1752B908>}
Seq Test f1 score (deep): 0.5970950704379984 
Seq Test accuracy score(deeo) : 0.6912487708947886 
              precision    recall  f1-score   support

           0       0.91      0.55      0.69       253
           1       0.91      0.08      0.14       278
           2       0.75      0.80      0.77       947
           3       0.52      0.94      0.67       214
           4       0.62      0.85      0.71       342

    accuracy                           0.69      2034
   macro avg       0.74      0.64      0.60      2034
weighted avg       0.75      0.69      0.66      2034

[[139   2  52   1  59]
 [ 13  21 132   6 106]
 [  0   0 755 179  13]
 [  0   0  12 202   0]
 [  0   0  53   0 289]]
Epoch 1/25
 - 319s - loss: 0.4676 - crf_marginal_accuracy: 0.5226 - val_loss: 0.1736 - val_crf_marginal_accuracy: 0.6233

Epoch 00001: v

100%|██████████| 2/2 [04:00<00:00, 120.28s/it]


{'20fold\\SC4031E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F2A10B508>, '20fold\\SC4032E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F2A10B188>}
Seq Test f1 score (deep): 0.7875767521261995 
Seq Test accuracy score(deeo) : 0.8658078368223295 
              precision    recall  f1-score   support

           0       0.94      0.87      0.90       276
           1       0.54      0.42      0.47       106
           2       0.87      0.93      0.90       885
           3       0.79      0.72      0.75       188
           4       0.91      0.91      0.91       408

    accuracy                           0.87      1863
   macro avg       0.81      0.77      0.79      1863
weighted avg       0.86      0.87      0.86      1863

[[239  15  15   0   7]
 [ 10  45  33   0  18]
 [  2  13 822  36  12]
 [  0   0  53 135   0]
 [  2  11  23   0 372]]
Epoch 1/25
 - 304s - loss: 0.3964 - crf_marginal_accuracy: 0.5787 - val_loss: 0.1184 - val_crf_marginal_accuracy: 0.6090

Epoch 00001: v

100%|██████████| 2/2 [05:59<00:00, 179.98s/it]


{'20fold\\SC4041E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0672D888>, '20fold\\SC4042E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0672D308>}
Seq Test f1 score (deep): 0.7128820193423099 
Seq Test accuracy score(deeo) : 0.7765913757700206 
              precision    recall  f1-score   support

           0       0.74      0.88      0.80       385
           1       0.48      0.35      0.40       303
           2       0.92      0.82      0.87      1134
           3       0.86      0.62      0.72       147
           4       0.67      0.92      0.77       466

    accuracy                           0.78      2435
   macro avg       0.73      0.72      0.71      2435
weighted avg       0.78      0.78      0.77      2435

[[339  17   2   1  26]
 [ 96 105  21   0  81]
 [  4  83 926  14 107]
 [  0   0  56  91   0]
 [ 20  15   1   0 430]]
Epoch 1/25
 - 322s - loss: 0.5279 - crf_marginal_accuracy: 0.4801 - val_loss: 0.3667 - val_crf_marginal_accuracy: 0.4371

Epoch 00001: v

100%|██████████| 2/2 [03:58<00:00, 119.40s/it]


{'20fold\\SC4051E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0A71EE08>, '20fold\\SC4052E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0A71E3C8>}
Seq Test f1 score (deep): 0.6555827328792337 
Seq Test accuracy score(deeo) : 0.7586027111574557 
              precision    recall  f1-score   support

           0       0.98      0.51      0.67       430
           1       0.66      0.12      0.20       158
           2       0.78      0.92      0.84       833
           3       0.89      0.90      0.89       249
           4       0.53      0.91      0.67       248

    accuracy                           0.76      1918
   macro avg       0.77      0.67      0.66      1918
weighted avg       0.80      0.76      0.74      1918

[[218   9 123   1  79]
 [  5  19  48   0  86]
 [  0   1 769  26  37]
 [  0   0  26 223   0]
 [  0   0  22   0 226]]
Epoch 1/25
 - 306s - loss: 0.4320 - crf_marginal_accuracy: 0.5500 - val_loss: 0.4690 - val_crf_marginal_accuracy: 0.5354

Epoch 00001: v

100%|██████████| 2/2 [04:03<00:00, 121.85s/it]


{'20fold\\SC4061E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F2A0DD7C8>, '20fold\\SC4062E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F2A0DD5C8>}
Seq Test f1 score (deep): 0.8355576553143 
Seq Test accuracy score(deeo) : 0.8913394298009683 
              precision    recall  f1-score   support

           0       0.87      0.89      0.88       335
           1       0.60      0.44      0.51       146
           2       0.92      0.93      0.93       824
           3       0.92      0.94      0.93       265
           4       0.90      0.97      0.93       289

    accuracy                           0.89      1859
   macro avg       0.84      0.83      0.84      1859
weighted avg       0.88      0.89      0.89      1859

[[298  33   2   0   2]
 [ 34  64  37   0  11]
 [ 11   8 766  22  17]
 [  0   0  16 249   0]
 [  0   1   8   0 280]]
Epoch 1/25
 - 300s - loss: 0.5288 - crf_marginal_accuracy: 0.4833 - val_loss: 0.2451 - val_crf_marginal_accuracy: 0.5483

Epoch 00001: val_

100%|██████████| 2/2 [05:12<00:00, 156.35s/it]


{'20fold\\SC4071E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F09055F88>, '20fold\\SC4072E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F09055288>}
Seq Test f1 score (deep): 0.8069981737971732 
Seq Test accuracy score(deeo) : 0.8746109381947532 
              precision    recall  f1-score   support

           0       0.92      0.96      0.94       531
           1       0.58      0.36      0.44       173
           2       0.89      0.93      0.91       795
           3       0.98      0.85      0.91       384
           4       0.77      0.90      0.83       366

    accuracy                           0.87      2249
   macro avg       0.83      0.80      0.81      2249
weighted avg       0.87      0.87      0.87      2249

[[511   9   1   0  10]
 [ 30  62  23   0  58]
 [  9  11 740   7  28]
 [  1   0  58 325   0]
 [  2  25  10   0 329]]
Epoch 1/25
 - 322s - loss: 0.5025 - crf_marginal_accuracy: 0.4923 - val_loss: 0.3573 - val_crf_marginal_accuracy: 0.4352

Epoch 00001: v

100%|██████████| 2/2 [05:11<00:00, 155.98s/it]


{'20fold\\SC4081E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0C94D0C8>, '20fold\\SC4082E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0C94D888>}
Seq Test f1 score (deep): 0.7803024844596744 
Seq Test accuracy score(deeo) : 0.8382084095063985 
              precision    recall  f1-score   support

           0       0.89      0.98      0.93       467
           1       0.49      0.39      0.44       107
           2       0.71      0.90      0.79       591
           3       0.98      0.72      0.83       632
           4       0.93      0.89      0.91       391

    accuracy                           0.84      2188
   macro avg       0.80      0.78      0.78      2188
weighted avg       0.85      0.84      0.84      2188

[[457   9   0   0   1]
 [ 52  42   6   0   7]
 [  2  31 530   9  19]
 [  2   3 169 458   0]
 [  1   0  43   0 347]]
Epoch 1/25
 - 316s - loss: 0.5119 - crf_marginal_accuracy: 0.4954 - val_loss: 1.0242 - val_crf_marginal_accuracy: 0.3766

Epoch 00001: v

100%|██████████| 2/2 [06:05<00:00, 182.54s/it]


{'20fold\\SC4091E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F237A1F88>, '20fold\\SC4092E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F237A1448>}
Seq Test f1 score (deep): 0.7999335163976934 
Seq Test accuracy score(deeo) : 0.8529280286097451 
              precision    recall  f1-score   support

           0       0.88      0.98      0.93       290
           1       0.57      0.49      0.53       100
           2       0.88      0.86      0.87      1073
           3       0.88      0.80      0.84       277
           4       0.82      0.86      0.84       497

    accuracy                           0.85      2237
   macro avg       0.80      0.80      0.80      2237
weighted avg       0.85      0.85      0.85      2237

[[284   4   1   0   1]
 [ 29  49  15   1   6]
 [  2  28 928  28  87]
 [  0   0  55 222   0]
 [  9   5  57   1 425]]
Epoch 1/25
 - 348s - loss: 0.5326 - crf_marginal_accuracy: 0.4728 - val_loss: 0.5821 - val_crf_marginal_accuracy: 0.3905

Epoch 00001: v

100%|██████████| 2/2 [05:28<00:00, 164.29s/it]


{'20fold\\SC4101E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1BC12DC8>, '20fold\\SC4102E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1BC122C8>}
Seq Test f1 score (deep): 0.6681030755990092 
Seq Test accuracy score(deeo) : 0.807832422586521 
              precision    recall  f1-score   support

           0       0.74      0.94      0.83       299
           1       0.58      0.45      0.50       182
           2       0.92      0.83      0.88      1278
           3       0.16      1.00      0.28        31
           4       0.96      0.77      0.86       406

    accuracy                           0.81      2196
   macro avg       0.67      0.80      0.67      2196
weighted avg       0.87      0.81      0.83      2196

[[ 281   11    6    1    0]
 [  52   81   48    1    0]
 [  10   28 1067  161   12]
 [   0    0    0   31    0]
 [  39   19   34    0  314]]
Epoch 1/25
 - 359s - loss: 0.5331 - crf_marginal_accuracy: 0.4706 - val_loss: 0.2758 - val_crf_marginal_accuracy

100%|██████████| 2/2 [03:50<00:00, 115.39s/it]


{'20fold\\SC4111E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F237FE548>, '20fold\\SC4112E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F237FE1C8>}
Seq Test f1 score (deep): 0.6568636899175695 
Seq Test accuracy score(deeo) : 0.6976878612716763 
              precision    recall  f1-score   support

           0       0.84      0.78      0.81       252
           1       0.62      0.32      0.43        31
           2       0.86      0.61      0.71       898
           3       0.68      0.80      0.74       240
           4       0.47      0.85      0.60       309

    accuracy                           0.70      1730
   macro avg       0.69      0.67      0.66      1730
weighted avg       0.76      0.70      0.70      1730

[[196   5   5   0  46]
 [  0  10  19   1   1]
 [ 24   0 545  88 241]
 [  0   0  33 192  15]
 [ 14   1  30   0 264]]
Epoch 1/25
 - 330s - loss: 0.4880 - crf_marginal_accuracy: 0.5031 - val_loss: 0.3071 - val_crf_marginal_accuracy: 0.6828

Epoch 00001: v

100%|██████████| 2/2 [04:31<00:00, 135.87s/it]


{'20fold\\SC4121E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1B1AC9C8>, '20fold\\SC4122E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1B1ACF08>}
Seq Test f1 score (deep): 0.7864998393898888 
Seq Test accuracy score(deeo) : 0.8491867915229176 
              precision    recall  f1-score   support

           0       0.97      0.85      0.91       466
           1       0.43      0.30      0.35       169
           2       0.81      0.91      0.86       750
           3       0.84      0.99      0.91       187
           4       0.93      0.89      0.91       457

    accuracy                           0.85      2029
   macro avg       0.80      0.79      0.79      2029
weighted avg       0.84      0.85      0.84      2029

[[396  46  14   2   8]
 [  6  50 100   0  13]
 [  5  16 686  33  10]
 [  0   0   2 185   0]
 [  2   4  45   0 406]]
Epoch 1/25
 - 341s - loss: 0.4005 - crf_marginal_accuracy: 0.5956 - val_loss: 0.1547 - val_crf_marginal_accuracy: 0.7256

Epoch 00001: v

100%|██████████| 2/2 [04:29<00:00, 135.00s/it]


{'20fold\\SC4141E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F09127908>, '20fold\\SC4142E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F09127548>}
Seq Test f1 score (deep): 0.7517269228642266 
Seq Test accuracy score(deeo) : 0.8486707566462167 
              precision    recall  f1-score   support

           0       1.00      0.78      0.87       368
           1       0.26      0.36      0.30        56
           2       0.77      0.99      0.87       790
           3       0.98      0.71      0.82       296
           4       0.99      0.81      0.89       446

    accuracy                           0.85      1956
   macro avg       0.80      0.73      0.75      1956
weighted avg       0.88      0.85      0.85      1956

[[286  52  27   0   3]
 [  0  20  36   0   0]
 [  0   2 782   5   1]
 [  0   0  86 210   0]
 [  0   2  82   0 362]]
Epoch 1/25
 - 311s - loss: 0.4167 - crf_marginal_accuracy: 0.5508 - val_loss: 0.2625 - val_crf_marginal_accuracy: 0.5536

Epoch 00001: v

100%|██████████| 2/2 [07:33<00:00, 226.96s/it]


{'20fold\\SC4151E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F14EC21C8>, '20fold\\SC4152E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F14EB4CC8>}
Seq Test f1 score (deep): 0.8651553016353741 
Seq Test accuracy score(deeo) : 0.9333087693441415 
              precision    recall  f1-score   support

           0       0.97      0.98      0.98       979
           1       0.54      0.58      0.56        88
           2       0.91      0.92      0.92       792
           3       0.92      0.94      0.93       355
           4       0.98      0.91      0.95       500

    accuracy                           0.93      2714
   macro avg       0.86      0.87      0.87      2714
weighted avg       0.93      0.93      0.93      2714

[[962  17   0   0   0]
 [ 21  51  16   0   0]
 [  4  20 729  31   8]
 [  1   1  19 334   0]
 [  1   6  36   0 457]]
Epoch 1/25
 - 314s - loss: 0.4134 - crf_marginal_accuracy: 0.5896 - val_loss: 0.1395 - val_crf_marginal_accuracy: 0.6714

Epoch 00001: v

100%|██████████| 2/2 [05:12<00:00, 156.11s/it]


{'20fold\\SC4161E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0F8C5EC8>, '20fold\\SC4162E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0F8D07C8>}
Seq Test f1 score (deep): 0.7030197911409679 
Seq Test accuracy score(deeo) : 0.7983232417326502 
              precision    recall  f1-score   support

           0       0.78      0.97      0.87       395
           1       0.33      0.37      0.35        97
           2       0.78      0.95      0.86       907
           3       0.98      0.54      0.70       293
           4       1.00      0.60      0.75       455

    accuracy                           0.80      2147
   macro avg       0.77      0.69      0.70      2147
weighted avg       0.83      0.80      0.79      2147

[[384  11   0   0   0]
 [ 48  36  13   0   0]
 [ 13  25 864   4   1]
 [  1   1 132 159   0]
 [ 45  36 103   0 271]]
Epoch 1/25
 - 327s - loss: 0.3846 - crf_marginal_accuracy: 0.6274 - val_loss: 0.4738 - val_crf_marginal_accuracy: 0.7172

Epoch 00001: v

100%|██████████| 2/2 [08:08<00:00, 244.40s/it]


{'20fold\\SC4171E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F44650088>, '20fold\\SC4172E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F44650048>}
Seq Test f1 score (deep): 0.6234066510712729 
Seq Test accuracy score(deeo) : 0.7034234234234235 
              precision    recall  f1-score   support

           0       0.96      0.54      0.69       865
           1       0.10      0.38      0.15        65
           2       0.82      0.67      0.74      1015
           3       0.64      0.96      0.77       403
           4       0.65      0.92      0.77       427

    accuracy                           0.70      2775
   macro avg       0.64      0.69      0.62      2775
weighted avg       0.80      0.70      0.72      2775

[[467 204  79   6 109]
 [ 12  25  16   4   8]
 [  5  29 681 208  92]
 [  0   0  18 385   0]
 [  0   0  33   0 394]]
Epoch 1/25
 - 328s - loss: 0.4251 - crf_marginal_accuracy: 0.5613 - val_loss: 0.2367 - val_crf_marginal_accuracy: 0.6170

Epoch 00001: v

100%|██████████| 2/2 [04:07<00:00, 123.74s/it]


{'20fold\\SC4181E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1B58E248>, '20fold\\SC4182E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F1B58E088>}
Seq Test f1 score (deep): 0.7398172302008332 
Seq Test accuracy score(deeo) : 0.8036093418259024 
              precision    recall  f1-score   support

           0       0.85      0.97      0.90       285
           1       0.71      0.26      0.38       180
           2       0.83      0.80      0.82       678
           3       0.89      0.87      0.88       507
           4       0.60      0.89      0.72       234

    accuracy                           0.80      1884
   macro avg       0.78      0.76      0.74      1884
weighted avg       0.81      0.80      0.79      1884

[[276   4   1   0   4]
 [ 31  47  34   0  68]
 [  8   6 543  52  69]
 [  6   0  62 439   0]
 [  4   9  12   0 209]]
Epoch 1/25
 - 307s - loss: 0.5210 - crf_marginal_accuracy: 0.4861 - val_loss: 0.4647 - val_crf_marginal_accuracy: 0.4288

Epoch 00001: v

100%|██████████| 2/2 [08:06<00:00, 243.25s/it]


{'20fold\\SC4191E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F450A5688>, '20fold\\SC4192E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F450A5308>}
Seq Test f1 score (deep): 0.7129811794959213 
Seq Test accuracy score(deeo) : 0.7999288002847988 
              precision    recall  f1-score   support

           0       0.73      0.89      0.80       564
           1       0.36      0.31      0.33       190
           2       0.90      0.87      0.89      1267
           3       0.65      0.99      0.79       170
           4       0.87      0.67      0.76       618

    accuracy                           0.80      2809
   macro avg       0.70      0.75      0.71      2809
weighted avg       0.81      0.80      0.80      2809

[[ 502   19   38    0    5]
 [  74   59   33    0   24]
 [   7   38 1101   90   31]
 [   0    0    2  168    0]
 [ 107   50   44    0  417]]
Epoch 1/25
 - 330s - loss: 0.4273 - crf_marginal_accuracy: 0.5516 - val_loss: 0.3100 - val_crf_marginal_accurac

100%|██████████| 1/1 [01:35<00:00, 95.96s/it]

{'20fold\\SC4231E0.npz': <numpy.lib.npyio.NpzFile object at 0x0000028F0A7CD108>}
Seq Test f1 score (deep): 0.8205738269822612 
Seq Test accuracy score(deeo) : 0.877431906614786 
              precision    recall  f1-score   support

           0       0.91      0.90      0.90       155
           1       0.49      0.51      0.50        57
           2       0.93      0.87      0.90       497
           3       0.90      0.93      0.92       147
           4       0.83      0.95      0.88       172

    accuracy                           0.88      1028
   macro avg       0.81      0.83      0.82      1028
weighted avg       0.88      0.88      0.88      1028

[[139   6   7   0   3]
 [ 12  29   7   0   9]
 [  2  24 434  15  22]
 [  0   0  10 137   0]
 [  0   0   9   0 163]]
Seq Test f1 score : 0.751526717197366 
Seq Test accuracy score : 0.8192304055970502 
              precision    recall  f1-score   support

           0       0.88      0.84      0.86      8285
           1       0.47

NameError: name 'plt' is not defined

In [110]:
print(confusion_matrix(gt_t, preds_t))

[[ 6980   520   374    26   385]
 [  566   976   683    14   565]
 [  115   392 15325  1087   880]
 [   13     5   912  4757    16]
 [  248   187   659     1  6622]]


# focal_weigted_loss20fold

In [38]:
%cd C:\Users\Admin\Desktop\ebrahi
from keras import backend as K
import models 
model=model_TCNN_CRF()
model.compile(optimizers.Adam(0.001,amsgrad=True),loss=FocalLoss_weighted, metrics=[crf_marginal_accuracy])

#/pure_aa
import gc
import random
base_path = "20fold"    
files = sorted(glob(os.path.join(base_path, "*.npz")))
j=0








gt_t=[]
preds_t=[]
preds_cat_cat=[]
kk=0
for i in range(20):
        ids = sorted(list(set([x.split("/")[-1][:5] for x in files])))
        ids=[x for x in files if x.split("/")[-1][:5] in ids]
        if kk<38:
            d=ids[kk:kk+2]
            idea=ids[kk+2:]+ids[0:kk]
            val=[idea.pop(int(kk/2)),idea.pop(int(kk/2)+1)]
            val_dict={k: np.load(k) for k in val}
            train_dict = {k: np.load(k) for k in idea}    
            test_dict = {k: np.load(k) for k in d}
        else :
            idea=ids[:38]
            d=ids[38]
            val=[idea.pop(int(kk/2)),idea.pop(int(kk/2)+1)]
            val_dict={k: np.load(k) for k in val}
            train_dict = {k: np.load(k) for k in idea}
            test_dict = {k: np.load(k) for k in [d]}
        kk=kk+2
        file_path = "bala.h5"
        checkpoint = ModelCheckpoint(file_path, monitor='acc',verbose=1, save_best_only=True, mode='max')
        early = EarlyStopping(monitor='acc', mode="max", patience=20, verbose=1)
        redonplat = ReduceLROnPlateau(monitor='acc', mode="max", factor=0.1, patience=4, verbose=2)#, factor=0.2
        callbacks_list = [checkpoint, early ,redonplat]
        
        model = get_base_model()
        
        #model.fit_generator(gen_balance(train_dict),validation_data=gen_j(val_dict),epochs=1,verbose=2,
         #                            steps_per_epoch=1000,validation_steps=300, callbacks=callbacks_list) 

        K.clear_session()
        del model
        
        gc.collect()
        file_path = "model1.h5"
        
        checkpoint = ModelCheckpoint(file_path, monitor='val_crf_marginal_accuracy',verbose=1, save_best_only=True, mode='max')
        early = EarlyStopping(monitor='val_crf_marginal_accuracy', mode="max", patience=20, verbose=1)
        redonplat = ReduceLROnPlateau(monitor='val_crf_marginal_accuracy', mode="max", factor=0.5, patience=4, verbose=2)#, factor=0.2
        callbacks_list = [checkpoint, early ,redonplat]
        model = get_base_model()
        model.fit_generator(gen_generator(train_dict),validation_data=gen_j(val_dict),epochs=25,verbose=2,
                                     steps_per_epoch=1000,validation_steps=300, callbacks=callbacks_list)
        
        K.clear_session()
        del model
        gc.collect()
        file_path = "model0.h5"
        checkpoint = ModelCheckpoint(file_path, monitor='val_crf_marginal_accuracy',verbose=1, save_best_only=True, mode='max')
        early = EarlyStopping(monitor='val_crf_marginal_accuracy', mode="max", patience=20, verbose=1)
        redonplat = ReduceLROnPlateau(monitor='val_crf_marginal_accuracy', mode="max", factor=0.5, patience=4, verbose=2)#, factor=0.2
        callbacks_list = [checkpoint, early ,redonplat]
        model = get_base_model()
        #model.load_weights('bala.h5')
        model.fit_generator(gen_j(train_dict),validation_data=gen_j(val_dict),epochs=25,verbose=2,
                                      steps_per_epoch=1000,validation_steps=300, callbacks=callbacks_list) 
        
        K.clear_session()
        del model
        gc.collect()
        
        h=0
        j=0
        gg=[]
        g=[]
        p=[]
        p_cat=[]
        for record in tqdm(test_dict):
                all_rows = test_dict[record]['x']
                
              
                l=0
                j=j+1
                for batch_hyp in chunker(range(all_rows.shape[0])):
                        l=l+1
                        X1 = all_rows[min(batch_hyp):max(batch_hyp)+1, ...]
                        Y1= test_dict[record]['y'][min(batch_hyp):max(batch_hyp)+1]
                        #######################################
                        X1 =rescale_array2(X1)
                        X1 = np.expand_dims(X1, 0)
                        model = get_base_model()
                        model.load_weights('model1.h5')
                        Y_pred1 = model.predict([X1,X1])
                        model.load_weights('model0.h5')
                        Y_pred0 = model.predict([X1,X1])
                        Y_pred=Y_pred1 +Y_pred0
                        Y_pred = Y_pred.argmax(axis=-1).ravel().tolist()
                        gt_t += Y1.ravel().tolist()
                        preds_t += Y_pred
                        g+=Y1.ravel().tolist()
                        p+=Y_pred
      #####
        print(test_dict)
        f1 = f1_score(g, p, average="macro")
        print("Seq Test f1 score (deep): %s "% f1)
        acc = accuracy_score(g, p)
        print("Seq Test accuracy score(deeo) : %s "% acc)
        print(classification_report(g, p))
        cnf_matrix = confusion_matrix(g, p)
        np.set_printoptions(precision=2)
        print(cnf_matrix)
        from keras import backend as K 
        K.clear_session()
        del model
f1 = f1_score(gt_t, preds_t, average="macro")
print("Seq Test f1 score : %s "% f1)
acc = accuracy_score(gt_t, preds_t)
print("Seq Test accuracy score : %s "% acc)
print(classification_report(gt_t, preds_t))
class_names=np.array([["W"], ["S1"],["S2"],["S3"],["R"]])
# Compute confusion matrix
import itertools
from sklearn.metrics import confusion_matrix
cnf_matrix = confusion_matrix(gt_t, preds_t)
print(cnf_matrix)


C:\Users\Admin\Desktop\ebrahi
Epoch 1/25
 - 233s - loss: 0.2534 - crf_marginal_accuracy: 0.5799 - val_loss: 0.1126 - val_crf_marginal_accuracy: 0.6860

Epoch 00001: val_crf_marginal_accuracy improved from -inf to 0.68600, saving model to model1.h5
Epoch 2/25
 - 230s - loss: 0.1244 - crf_marginal_accuracy: 0.6781 - val_loss: 0.1633 - val_crf_marginal_accuracy: 0.6888

Epoch 00002: val_crf_marginal_accuracy improved from 0.68600 to 0.68883, saving model to model1.h5
Epoch 3/25
 - 230s - loss: 0.1226 - crf_marginal_accuracy: 0.6844 - val_loss: 0.0732 - val_crf_marginal_accuracy: 0.7319

Epoch 00003: val_crf_marginal_accuracy improved from 0.68883 to 0.73193, saving model to model1.h5
Epoch 4/25
 - 230s - loss: 0.1100 - crf_marginal_accuracy: 0.7018 - val_loss: 0.2612 - val_crf_marginal_accuracy: 0.7610

Epoch 00004: val_crf_marginal_accuracy improved from 0.73193 to 0.76097, saving model to model1.h5
Epoch 5/25
 - 230s - loss: 0.1025 - crf_marginal_accuracy: 0.7317 - val_loss: 0.0653 - va

100%|██████████| 2/2 [04:09<00:00, 124.84s/it]


{'20fold\\SC4001E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001EEEEB1F448>, '20fold\\SC4002E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001EEEEB1F888>}
Seq Test f1 score (deep): 0.8050763759334203 
Seq Test accuracy score(deeo) : 0.8673780487804879 
              precision    recall  f1-score   support

           0       0.92      0.92      0.92       371
           1       0.51      0.40      0.45       117
           2       0.84      0.90      0.87       623
           3       0.97      0.83      0.89       517
           4       0.82      0.96      0.89       340

    accuracy                           0.87      1968
   macro avg       0.81      0.80      0.81      1968
weighted avg       0.87      0.87      0.86      1968

[[341  19   1   0  10]
 [ 24  47  10   0  36]
 [  1  21 563  14  24]
 [  2   0  86 429   0]
 [  1   5   7   0 327]]
Epoch 1/25
 - 228s - loss: 0.2402 - crf_marginal_accuracy: 0.5562 - val_loss: 0.2065 - val_crf_marginal_accuracy: 0.4764

Epoch 00001: v

100%|██████████| 2/2 [05:38<00:00, 169.29s/it]


{'20fold\\SC4011E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001EEEEB1F348>, '20fold\\SC4012E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001EEE52FB248>}
Seq Test f1 score (deep): 0.6454703495680274 
Seq Test accuracy score(deeo) : 0.746177370030581 
              precision    recall  f1-score   support

           0       0.58      0.50      0.54       319
           1       0.48      0.30      0.37       201
           2       0.86      0.87      0.87      1222
           3       0.71      0.93      0.81       201
           4       0.60      0.69      0.64       346

    accuracy                           0.75      2289
   macro avg       0.65      0.66      0.65      2289
weighted avg       0.74      0.75      0.74      2289

[[ 159   14   99    2   45]
 [  40   61   46    1   53]
 [  12   15 1061   72   62]
 [   0    0   14  187    0]
 [  61   37    8    0  240]]
Epoch 1/25
 - 235s - loss: 0.2319 - crf_marginal_accuracy: 0.5892 - val_loss: 0.1312 - val_crf_marginal_accuracy

100%|██████████| 2/2 [04:48<00:00, 144.30s/it]


{'20fold\\SC4021E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F2403D6748>, '20fold\\SC4022E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F2403D6CC8>}
Seq Test f1 score (deep): 0.68834468751412 
Seq Test accuracy score(deeo) : 0.7748279252704031 
              precision    recall  f1-score   support

           0       0.71      0.95      0.81       253
           1       0.89      0.12      0.20       278
           2       0.85      0.83      0.84       947
           3       0.60      0.95      0.74       214
           4       0.79      0.91      0.85       342

    accuracy                           0.77      2034
   macro avg       0.77      0.75      0.69      2034
weighted avg       0.80      0.77      0.74      2034

[[240   0   2   1  10]
 [ 94  32  99   9  44]
 [  2   3 788 126  28]
 [  0   0  10 204   0]
 [  2   1  27   0 312]]
Epoch 1/25
 - 234s - loss: 0.2991 - crf_marginal_accuracy: 0.4678 - val_loss: 0.2846 - val_crf_marginal_accuracy: 0.6282

Epoch 00001: val

100%|██████████| 2/2 [04:02<00:00, 121.13s/it]


{'20fold\\SC4031E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F24E1D9B48>, '20fold\\SC4032E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F24E1D9C48>}
Seq Test f1 score (deep): 0.7449436933685125 
Seq Test accuracy score(deeo) : 0.8293075684380032 
              precision    recall  f1-score   support

           0       0.88      0.89      0.88       276
           1       0.49      0.44      0.47       106
           2       0.85      0.90      0.88       885
           3       0.65      0.62      0.63       188
           4       0.90      0.84      0.87       408

    accuracy                           0.83      1863
   macro avg       0.75      0.74      0.74      1863
weighted avg       0.83      0.83      0.83      1863

[[245   9   6  11   5]
 [ 13  47  30   0  16]
 [  4  17 796  52  16]
 [  1   0  71 116   0]
 [ 16  23  28   0 341]]
Epoch 1/25
 - 237s - loss: 0.3032 - crf_marginal_accuracy: 0.4815 - val_loss: 0.4161 - val_crf_marginal_accuracy: 0.3603

Epoch 00001: v

100%|██████████| 2/2 [06:18<00:00, 189.47s/it]


{'20fold\\SC4041E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F23FDC38C8>, '20fold\\SC4042E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F23FD9BD88>}
Seq Test f1 score (deep): 0.6171221844064336 
Seq Test accuracy score(deeo) : 0.7186858316221766 
              precision    recall  f1-score   support

           0       0.80      0.61      0.69       385
           1       0.66      0.20      0.31       303
           2       0.86      0.83      0.84      1134
           3       0.95      0.41      0.57       147
           4       0.51      0.98      0.67       466

    accuracy                           0.72      2435
   macro avg       0.76      0.60      0.62      2435
weighted avg       0.76      0.72      0.70      2435

[[235   9  17   0 124]
 [ 54  61  47   0 141]
 [  3  18 939   3 171]
 [  0   0  87  60   0]
 [  2   4   5   0 455]]
Epoch 1/25
 - 231s - loss: 0.3318 - crf_marginal_accuracy: 0.4704 - val_loss: 0.2113 - val_crf_marginal_accuracy: 0.4399

Epoch 00001: v

100%|██████████| 2/2 [04:04<00:00, 122.11s/it]


{'20fold\\SC4051E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F238334C88>, '20fold\\SC4052E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F238334048>}
Seq Test f1 score (deep): 0.65388801607617 
Seq Test accuracy score(deeo) : 0.7440041710114703 
              precision    recall  f1-score   support

           0       0.90      0.57      0.70       430
           1       0.48      0.17      0.25       158
           2       0.79      0.88      0.83       833
           3       0.97      0.69      0.80       249
           4       0.52      1.00      0.68       248

    accuracy                           0.74      1918
   macro avg       0.73      0.66      0.65      1918
weighted avg       0.78      0.74      0.73      1918

[[246  12  95   1  76]
 [ 22  27  26   0  83]
 [  5  17 736   5  70]
 [  0   0  78 171   0]
 [  0   0   1   0 247]]
Epoch 1/25
 - 238s - loss: 0.3227 - crf_marginal_accuracy: 0.4716 - val_loss: 0.1601 - val_crf_marginal_accuracy: 0.6318

Epoch 00001: val

100%|██████████| 2/2 [04:05<00:00, 122.50s/it]


{'20fold\\SC4061E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F25C5AA588>, '20fold\\SC4062E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F25C5AA208>}
Seq Test f1 score (deep): 0.8461594771349027 
Seq Test accuracy score(deeo) : 0.8956428187197418 
              precision    recall  f1-score   support

           0       0.89      0.96      0.92       335
           1       0.74      0.46      0.57       146
           2       0.91      0.93      0.92       824
           3       0.92      0.88      0.90       265
           4       0.87      0.96      0.92       289

    accuracy                           0.90      1859
   macro avg       0.87      0.84      0.85      1859
weighted avg       0.89      0.90      0.89      1859

[[321   7   2   0   5]
 [ 34  67  31   0  14]
 [  6  13 765  19  21]
 [  0   0  31 234   0]
 [  0   3   8   0 278]]
Epoch 1/25
 - 232s - loss: 0.3020 - crf_marginal_accuracy: 0.4865 - val_loss: 0.2394 - val_crf_marginal_accuracy: 0.4423

Epoch 00001: v

100%|██████████| 2/2 [05:23<00:00, 161.81s/it]


{'20fold\\SC4071E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F23DEEFF48>, '20fold\\SC4072E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F23DEEFCC8>}
Seq Test f1 score (deep): 0.8096433558654089 
Seq Test accuracy score(deeo) : 0.8692752334370831 
              precision    recall  f1-score   support

           0       0.97      0.94      0.95       531
           1       0.81      0.35      0.49       173
           2       0.83      0.93      0.88       795
           3       0.99      0.78      0.87       384
           4       0.77      0.97      0.86       366

    accuracy                           0.87      2249
   macro avg       0.87      0.79      0.81      2249
weighted avg       0.88      0.87      0.86      2249

[[500   6  23   0   2]
 [ 16  60  37   0  60]
 [  2   6 739   2  46]
 [  0   0  84 300   0]
 [  0   2   8   0 356]]
Epoch 1/25
 - 239s - loss: 0.3026 - crf_marginal_accuracy: 0.4846 - val_loss: 0.2994 - val_crf_marginal_accuracy: 0.4390

Epoch 00001: v

100%|██████████| 2/2 [05:27<00:00, 163.90s/it]


{'20fold\\SC4081E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F236D63788>, '20fold\\SC4082E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F236D633C8>}
Seq Test f1 score (deep): 0.6868923796580358 
Seq Test accuracy score(deeo) : 0.7449725776965265 
              precision    recall  f1-score   support

           0       0.87      0.97      0.92       467
           1       0.52      0.25      0.34       107
           2       0.56      0.93      0.70       591
           3       1.00      0.42      0.60       632
           4       0.92      0.85      0.89       391

    accuracy                           0.74      2188
   macro avg       0.77      0.69      0.69      2188
weighted avg       0.82      0.74      0.73      2188

[[452   8   4   0   3]
 [ 59  27  16   0   5]
 [  7  15 549   0  20]
 [  0   1 363 268   0]
 [  2   1  54   0 334]]
Epoch 1/25
 - 237s - loss: 0.3144 - crf_marginal_accuracy: 0.4676 - val_loss: 0.4624 - val_crf_marginal_accuracy: 0.3798

Epoch 00001: v

100%|██████████| 2/2 [06:00<00:00, 180.07s/it]


{'20fold\\SC4091E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F24DE0A948>, '20fold\\SC4092E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F24DE0A588>}
Seq Test f1 score (deep): 0.7424496017843764 
Seq Test accuracy score(deeo) : 0.8332588287885561 
              precision    recall  f1-score   support

           0       0.89      0.88      0.88       290
           1       0.44      0.22      0.29       100
           2       0.84      0.87      0.86      1073
           3       0.87      0.84      0.86       277
           4       0.81      0.84      0.82       497

    accuracy                           0.83      2237
   macro avg       0.77      0.73      0.74      2237
weighted avg       0.82      0.83      0.83      2237

[[254   3  27   0   6]
 [ 28  22  33   2  15]
 [  4  21 935  33  80]
 [  0   0  43 234   0]
 [  0   4  74   0 419]]
Epoch 1/25
 - 319s - loss: 0.3020 - crf_marginal_accuracy: 0.4705 - val_loss: 0.2876 - val_crf_marginal_accuracy: 0.3720

Epoch 00001: v

100%|██████████| 2/2 [05:26<00:00, 163.02s/it]


{'20fold\\SC4101E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F245810E88>, '20fold\\SC4102E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F245810B08>}
Seq Test f1 score (deep): 0.6919504493945001 
Seq Test accuracy score(deeo) : 0.8465391621129326 
              precision    recall  f1-score   support

           0       0.92      0.85      0.89       299
           1       0.67      0.31      0.42       182
           2       0.91      0.88      0.90      1278
           3       0.22      1.00      0.35        31
           4       0.85      0.95      0.90       406

    accuracy                           0.85      2196
   macro avg       0.72      0.80      0.69      2196
weighted avg       0.87      0.85      0.85      2196

[[ 255   15   21    0    8]
 [  18   56   69    1   38]
 [   3   11 1131  112   21]
 [   0    0    0   31    0]
 [   1    1   18    0  386]]
Epoch 1/25
 - 237s - loss: 0.2519 - crf_marginal_accuracy: 0.5672 - val_loss: 0.0674 - val_crf_marginal_accurac

100%|██████████| 2/2 [03:42<00:00, 111.48s/it]


{'20fold\\SC4111E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F25667AE08>, '20fold\\SC4112E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F25667AAC8>}
Seq Test f1 score (deep): 0.6691876583323181 
Seq Test accuracy score(deeo) : 0.6820809248554913 
              precision    recall  f1-score   support

           0       0.84      0.73      0.78       252
           1       0.51      0.58      0.55        31
           2       0.92      0.53      0.67       898
           3       0.60      0.85      0.70       240
           4       0.48      0.96      0.64       309

    accuracy                           0.68      1730
   macro avg       0.67      0.73      0.67      1730
weighted avg       0.78      0.68      0.69      1730

[[184   9   4   0  55]
 [  1  18   8   3   1]
 [ 30   6 477 134 251]
 [  3   0  18 205  14]
 [  0   2  11   0 296]]
Epoch 1/25
 - 244s - loss: 0.3080 - crf_marginal_accuracy: 0.4799 - val_loss: 0.1991 - val_crf_marginal_accuracy: 0.4248

Epoch 00001: v

100%|██████████| 2/2 [04:33<00:00, 136.67s/it]


{'20fold\\SC4121E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F2458A8E08>, '20fold\\SC4122E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F2458A8688>}
Seq Test f1 score (deep): 0.6337645544920127 
Seq Test accuracy score(deeo) : 0.7111877772301627 
              precision    recall  f1-score   support

           0       0.85      0.41      0.56       466
           1       0.16      0.15      0.16       169
           2       0.73      0.93      0.82       750
           3       0.86      0.91      0.88       187
           4       0.73      0.78      0.75       457

    accuracy                           0.71      2029
   macro avg       0.67      0.64      0.63      2029
weighted avg       0.72      0.71      0.69      2029

[[192 104  64   3 103]
 [  3  26 122   0  18]
 [  0  14 698  25  13]
 [  0   0  17 170   0]
 [ 30  15  55   0 357]]
Epoch 1/25
 - 234s - loss: 0.2801 - crf_marginal_accuracy: 0.5036 - val_loss: 0.2345 - val_crf_marginal_accuracy: 0.3877

Epoch 00001: v

100%|██████████| 2/2 [04:33<00:00, 136.72s/it]


{'20fold\\SC4141E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F22CC52BC8>, '20fold\\SC4142E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F22CC52788>}
Seq Test f1 score (deep): 0.6342596679356389 
Seq Test accuracy score(deeo) : 0.754601226993865 
              precision    recall  f1-score   support

           0       1.00      0.60      0.75       368
           1       0.07      0.09      0.08        56
           2       0.66      1.00      0.80       790
           3       0.99      0.79      0.88       296
           4       0.96      0.52      0.67       446

    accuracy                           0.75      1956
   macro avg       0.74      0.60      0.63      1956
weighted avg       0.83      0.75      0.75      1956

[[219  69  74   0   6]
 [  0   5  48   0   3]
 [  0   0 787   2   1]
 [  0   0  63 233   0]
 [  0   2 212   0 232]]
Epoch 1/25
 - 234s - loss: 0.3020 - crf_marginal_accuracy: 0.4697 - val_loss: 0.2442 - val_crf_marginal_accuracy: 0.4669

Epoch 00001: va

100%|██████████| 2/2 [08:16<00:00, 248.29s/it]


{'20fold\\SC4151E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F23F31A608>, '20fold\\SC4152E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F23F31A288>}
Seq Test f1 score (deep): 0.7848476790208457 
Seq Test accuracy score(deeo) : 0.841930729550479 
              precision    recall  f1-score   support

           0       0.97      0.74      0.84       979
           1       0.38      0.49      0.43        88
           2       0.73      0.92      0.82       792
           3       0.88      0.94      0.91       355
           4       0.96      0.91      0.93       500

    accuracy                           0.84      2714
   macro avg       0.78      0.80      0.78      2714
weighted avg       0.87      0.84      0.84      2714

[[721  57 190   2   9]
 [ 23  43  15   0   7]
 [  1  11 730  45   5]
 [  0   1  20 334   0]
 [  0   0  43   0 457]]
Epoch 1/25
 - 245s - loss: 0.2941 - crf_marginal_accuracy: 0.5188 - val_loss: 0.3347 - val_crf_marginal_accuracy: 0.5388

Epoch 00001: va

100%|██████████| 2/2 [05:32<00:00, 166.00s/it]


{'20fold\\SC4161E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F237FF31C8>, '20fold\\SC4162E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F237FF3748>}
Seq Test f1 score (deep): 0.7172876837304089 
Seq Test accuracy score(deeo) : 0.8020493712156498 
              precision    recall  f1-score   support

           0       0.76      0.96      0.85       395
           1       0.29      0.39      0.33        97
           2       0.82      0.90      0.86       907
           3       0.91      0.69      0.79       293
           4       0.94      0.64      0.76       455

    accuracy                           0.80      2147
   macro avg       0.75      0.71      0.72      2147
weighted avg       0.82      0.80      0.80      2147

[[379  15   0   0   1]
 [ 49  38   6   0   4]
 [ 21  41 814  19  12]
 [  1   0  90 202   0]
 [ 48  36  82   0 289]]
Epoch 1/25
 - 238s - loss: 0.3062 - crf_marginal_accuracy: 0.4806 - val_loss: 0.1368 - val_crf_marginal_accuracy: 0.2065

Epoch 00001: v

100%|██████████| 2/2 [09:05<00:00, 272.95s/it]


{'20fold\\SC4171E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F27FD58DC8>, '20fold\\SC4172E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F27FD58A08>}
Seq Test f1 score (deep): 0.706714487934124 
Seq Test accuracy score(deeo) : 0.8104504504504505 
              precision    recall  f1-score   support

           0       0.96      0.85      0.90       865
           1       0.29      0.25      0.26        65
           2       0.80      0.77      0.79      1015
           3       0.69      0.90      0.78       403
           4       0.78      0.82      0.80       427

    accuracy                           0.81      2775
   macro avg       0.70      0.72      0.71      2775
weighted avg       0.82      0.81      0.81      2775

[[737  30  55   7  36]
 [ 22  16  23   2   2]
 [  7   8 783 156  61]
 [  0   0  39 364   0]
 [  0   2  76   0 349]]
Epoch 1/25
 - 249s - loss: 0.2654 - crf_marginal_accuracy: 0.5304 - val_loss: 0.2101 - val_crf_marginal_accuracy: 0.5845

Epoch 00001: va

100%|██████████| 2/2 [04:09<00:00, 124.97s/it]


{'20fold\\SC4181E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F24D7B4908>, '20fold\\SC4182E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F24D7B4548>}
Seq Test f1 score (deep): 0.5940909882110719 
Seq Test accuracy score(deeo) : 0.6656050955414012 
              precision    recall  f1-score   support

           0       0.56      0.98      0.71       285
           1       0.57      0.13      0.22       180
           2       0.69      0.66      0.68       678
           3       0.99      0.64      0.78       507
           4       0.48      0.75      0.58       234

    accuracy                           0.67      1884
   macro avg       0.66      0.63      0.59      1884
weighted avg       0.71      0.67      0.65      1884

[[278   2   1   0   4]
 [ 79  24  28   0  49]
 [ 74  11 450   4 139]
 [ 14   0 166 327   0]
 [ 49   5   5   0 175]]
Epoch 1/25
 - 238s - loss: 0.2485 - crf_marginal_accuracy: 0.5740 - val_loss: 0.1696 - val_crf_marginal_accuracy: 0.6837

Epoch 00001: v

100%|██████████| 2/2 [09:09<00:00, 274.64s/it]


{'20fold\\SC4191E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F283CC7548>, '20fold\\SC4192E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F283CC7348>}
Seq Test f1 score (deep): 0.6763509915461556 
Seq Test accuracy score(deeo) : 0.7582769668921324 
              precision    recall  f1-score   support

           0       0.86      0.56      0.68       564
           1       0.48      0.21      0.29       190
           2       0.74      0.93      0.83      1267
           3       0.81      0.91      0.86       170
           4       0.76      0.71      0.73       618

    accuracy                           0.76      2809
   macro avg       0.73      0.66      0.68      2809
weighted avg       0.76      0.76      0.74      2809

[[ 318   23  170    0   53]
 [  38   39   66    0   47]
 [   2    7 1183   36   39]
 [   0    0   16  154    0]
 [  12   13  157    0  436]]
Epoch 1/25
 - 238s - loss: 0.3009 - crf_marginal_accuracy: 0.5278 - val_loss: 0.1886 - val_crf_marginal_accurac

100%|██████████| 1/1 [01:25<00:00, 85.67s/it]

{'20fold\\SC4231E0.npz': <numpy.lib.npyio.NpzFile object at 0x000001F22D9F6DC8>}
Seq Test f1 score (deep): 0.8001588830857124 
Seq Test accuracy score(deeo) : 0.8628404669260701 
              precision    recall  f1-score   support

           0       0.89      0.90      0.90       155
           1       0.46      0.44      0.45        57
           2       0.94      0.83      0.88       497
           3       0.81      0.99      0.89       147
           4       0.82      0.94      0.88       172

    accuracy                           0.86      1028
   macro avg       0.79      0.82      0.80      1028
weighted avg       0.87      0.86      0.86      1028

[[140   6   5   2   2]
 [ 14  25   9   0   9]
 [  3  23 414  33  24]
 [  0   0   1 146   0]
 [  0   0  10   0 162]]
Seq Test f1 score : 0.7113416722750381 
Seq Test accuracy score : 0.7873688191358609 
              precision    recall  f1-score   support

           0       0.86      0.77      0.81      8285
           1       0.

In [35]:
np.unique(b[0,:,0])


array([1, 2, 4])